import { notFound } from "next/navigation";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { formatEuro } from "@/lib/order";
import { DEFAULT_WHATSAPP_TEMPLATE, renderWhatsAppMessage, whatsappUrl } from "@/lib/whatsapp";
import type { Order } from "@/lib/types";
import { addNote,cancelOrder,selfAssign,updateOrder } from "./actions";
import { WhatsAppButton } from "./whatsapp-button";

export const dynamic="force-dynamic";
export default async function OrderDetail({params}:{params:Promise<{id:string}>}){const {id}=await params;const s=await createServerSupabaseClient();const {data:{user}}=await s.auth.getUser();
  const [{data:o},{data:profiles},{data:notes},{data:activity},{data:template},{data:bank},{data:me}]=await Promise.all([
    s.from("orders").select("*").eq("id",id).single<Order>(),s.from("profiles").select("id,full_name").eq("disabled",false).order("full_name"),s.from("internal_notes").select("*,profiles(full_name)").eq("order_id",id).order("created_at",{ascending:false}),s.from("activity_log").select("*,profiles(full_name)").eq("order_id",id).order("created_at",{ascending:false}),s.from("message_templates").select("body").eq("key","ordine_pronto").single(),s.from("app_settings").select("value").eq("key","bank_details").single(),s.from("profiles").select("full_name,presentation").eq("id",user!.id).single()
  ]);if(!o)notFound(); const message=renderWhatsAppMessage(template?.body??DEFAULT_WHATSAPP_TEMPLATE,o,me??{full_name:"Collaboratore Astreo",presentation:""},bank?.value??"");
  return <><p className="eyebrow">{o.code}</p><h1>{o.customer_name}</h1>{o.cancelled_at&&<p className="error">Ordine annullato: {o.cancellation_reason}</p>}<div className="detail-grid"><section className="card"><h2>Ordine</h2><p><strong>Telefono:</strong> {o.phone}<br/><strong>Quantità:</strong> {o.cases_quantity} casse / {o.bottles_quantity} bottiglie<br/><strong>Modalità:</strong> {o.fulfillment_type}<br/><strong>Indirizzo:</strong> {o.shipping_address??"Via Spesse 5, 36070 Brogliano (VI)"}<br/><strong>Totale:</strong> {formatEuro(o.expected_total_cents)}<br/><strong>Note cliente:</strong> {o.notes??"—"}</p><form action={updateOrder.bind(null,id)}><div className="field"><label>Collaboratore</label><select name="assigneeId" defaultValue={o.assignee_id??""}><option value="">Non assegnato</option>{profiles?.map(p=><option key={p.id} value={p.id}>{p.full_name||"Collaboratore senza nome"}</option>)}</select></div><div className="field"><label>Contatto</label><select name="contactStatus" defaultValue={o.contact_status}><option value="da_contattare">Da contattare</option><option value="contattato">Contattato</option><option value="confermato">Confermato</option></select></div><div className="field"><label>Pagamento</label><select name="paymentStatus" defaultValue={o.payment_status}><option value="non_pagato">Non pagato</option><option value="parziale">Parziale</option><option value="pagato">Pagato</option></select><small className="muted">Quando segni “Pagato”, il totale dell’ordine viene registrato automaticamente come incassato.</small></div><div className="field"><label>Consegna</label><select name="deliveryStatus" defaultValue={o.delivery_status}><option value="da_programmare">Da programmare</option><option value="programmata">Programmata</option><option value="consegnata">Consegnata</option></select></div><div className="radio-row"><button className="button">Salva</button><button formAction={selfAssign.bind(null,id)} className="button secondary">Assegna a me</button></div></form></section>
    <section className="card"><h2>WhatsApp</h2><textarea readOnly value={message} style={{minHeight:330}}/><WhatsAppButton id={id} url={whatsappUrl(o.phone,message)}/></section></div>
    <div className="detail-grid" style={{marginTop:"1.2rem"}}><section className="card"><h2>Note interne</h2><form action={addNote.bind(null,id)}><textarea name="body" required maxLength={2000}/><button className="button">Aggiungi nota</button></form><ul className="timeline">{notes?.map(n=><li key={n.id}><strong>{n.profiles?.full_name}</strong><br/>{n.body}<br/><small className="muted">{new Date(n.created_at).toLocaleString("it-IT")}</small></li>)}</ul></section><section className="card"><h2>Storico</h2><ul className="timeline">{activity?.map(a=><li key={a.id}><strong>{a.action.replaceAll("_"," ")}</strong> · {a.profiles?.full_name??"Sistema"}<br/><small className="muted">{new Date(a.created_at).toLocaleString("it-IT")}</small></li>)}</ul>{!o.cancelled_at&&<form action={cancelOrder.bind(null,id)}><div className="field"><label>Motivo annullamento</label><input name="reason" required minLength={3}/></div><button className="button danger">Annulla ordine</button></form>}</section></div></>;
}
